[[redirects]]
from = "/newsletter/what-are-good-metrics/"
to = "/en/blog/what-are-good-metrics/"
status = 301

[[redirects]]
from = "/newsletter/where-to-start-when-your-business-isnt-running/"
to = "/en/blog/where-to-start-when-your-business-isnt-running/"
status = 301

[[redirects]]
from = "/newsletter/why-do-people-decide-the-way-they-do/"
to = "/en/blog/why-do-people-decide-the-way-they-do/"
status = 301

[[redirects]]
from = "/newsletter/how-to-challenge-your-own-beliefs/"
to = "/en/blog/how-to-challenge-your-own-beliefs/"
status = 301

[[redirects]]
from = "/newsletter/structuring-unlearned-information/"
to = "/en/blog/structuring-unlearned-information/"
status = 301

[[redirects]]
from = "/newsletter/what-makes-your-business-fit/"
to = "/en/blog/what-makes-your-business-fit/"
status = 301

[[redirects]]
from = "/newsletter/we-are-so-close/"
to = "/en/blog/we-are-so-close/"
status = 301

[[redirects]]
from = "/newsletter/he-who-knows-not-does-not-buy/"
to = "/en/blog/he-who-knows-not-does-not-buy/"
status = 301

[[redirects]]
from = "/newsletter/five-steps-to-ask-better-questions/"
to = "/en/blog/five-steps-to-ask-better-questions/"
status = 301

[[redirects]]
from = "/newsletter/we-assume-a-world-that-isnt-there/"
to = "/en/blog/we-assume-a-world-that-isnt-there/"
status = 301

[[redirects]]
from = "/newsletter/how-to-speed-up-customer-research/"
to = "/en/blog/how-to-speed-up-customer-research/"
status = 301
from = "/podcast/deutsche-telekoms-dirk-roeder-navigating-blockchain-and-bitcoin-in-the-corporate-world/"
to = ""

[[redirects]]
from = "/newsletter/how-to-achieve-product-language-fit/"
to = "/en/blog/how-to-achieve-product-language-fit/"
status = 301

[[redirects]]
from = "/newsletter/would-you-rather-eat-a-dolphin-or-buy-our-product/"
to = "/en/blog/would-you-rather-eat-a-dolphin-or-buy-our-product/"
status = 301

[[redirects]]
from = "/newsletter/picture-outtakes/0"
to = "/en/blog/picture-outtakes/0"
status = 301

[[redirects]]
from = "/newsletter/confusing-correlation-with-causality/"
to = "/en/blog/confusing-correlation-with-causality/"
status = 301

[[redirects]]
from = "/newsletter/knowing-when-to-act-insecure/"
to = "/en/blog/knowing-when-to-act-insecure/"
status = 301

[[redirects]]
from = "/newsletter/its-not-about-your-progress/"
to = "/en/blog/its-not-about-your-progress/"
status = 301

[[redirects]]
from = "/newsletter/why-people-stay-in-jobs-they-dont-like/"
to = "/en/blog/why-people-stay-in-jobs-they-dont-like/"
status = 301

[[redirects]]
from = "/newsletter/most-important-business-skills/"
to = "/en/blog/most-important-business-skills/"
status = 301

[[redirects]]
from = "/newsletter/how-to-make-this-year-special/"
to = "/en/blog/how-to-make-this-year-special/"
status = 301

[[redirects]]
from = "/newsletter/how-to-avoid-customers-trying-to-negotiate-your-prices-down/"
to = "/en/blog/how-to-avoid-customers-trying-to-negotiate-your-prices-down/"
status = 301

[[redirects]]
from = "/newsletter/why-talking-to-your-customers-sometimes-feels-hard/"
to = "/en/blog/why-talking-to-your-customers-sometimes-feels-hard/"
status = 301

[[redirects]]
from = "/newsletter/are-personas-useful-for-product-development/"
to = "/en/blog/are-personas-useful-for-product-development/"
status = 301

[[redirects]]
from = "/newsletter/understanding-the-jobs-to-be-done-perspective/"
to = "/en/blog/understanding-the-jobs-to-be-done-perspective/"
status = 301

[[redirects]]
from = "/newsletter/how-to-have-good-customer-interviews/"
to = "/en/blog/how-to-have-good-customer-interviews/"
status = 301

[[redirects]]
from = "/newsletter/how-to-avoid-the-confirming-research-bias/"
to = "/en/blog/how-to-avoid-the-confirming-research-bias/"
status = 301

[[redirects]]
from = "/newsletter/how-to-separate-problem-and-solution/"
to = "/en/blog/how-to-separate-problem-and-solution/"
status = 301

[[redirects]]
from = "/newsletter/the-power-of-writing/"
to = "/en/blog/the-power-of-writing/"
status = 301

[[redirects]]
from = "/newsletter/the-missing-dimension-in-building-sustainable-products/"
to = "/en/blog/the-missing-dimension-in-building-sustainable-products/"
status = 301

[[redirects]]
from = "/newsletter/your-language-limits-your-achievements/"
to = "/en/blog/your-language-limits-your-achievements/"
status = 301

[[redirects]]
from = "/newsletter/why-do-companies-buy-customer-research-at-all/"
to = "/en/blog/why-do-companies-buy-customer-research-at-all/"
status = 301

[[redirects]]
from = "/newsletter/how-to-convince-your-boss/"
to = "/en/blog/how-to-convince-your-boss/"
status = 301

[[redirects]]
from = "/newsletter/how-to-get-your-customers-attention/"
to = "/en/blog/how-to-get-your-customers-attention/"
status = 301

[[redirects]]
from = "/newsletter/questioning-artificial-intelligence/"
to = "/en/blog/questioning-artificial-intelligence/"
status = 301

[[redirects]]
from = "/newsletter/the-stories-we-tell-ourselves-when-we-fail/"
to = "/en/blog/the-stories-we-tell-ourselves-when-we-fail/"
status = 301

[[redirects]]
from = "/newsletter/can-ai-do-user-research/"
to = "/en/blog/can-ai-do-user-research/"
status = 301

[[redirects]]
from = "/newsletter/how-much-should-i-invest-in-user-research/"
to = "/en/blog/how-much-should-i-invest-in-user-research/"
status = 301

[[redirects]]
from = "/newsletter/why-companies-fail-to-act-on-their-user-research/"
to = "/en/blog/why-companies-fail-to-act-on-their-user-research/"
status = 301

[[redirects]]
from = "/newsletter/whats-the-difference-between-user-research-and-customer-research/"
to = "/en/blog/whats-the-difference-between-user-research-and-customer-research/"
status = 301

[[redirects]]
from = "/newsletter/where-to-start-with-everyday-customer-interviews/"
to = "/en/blog/where-to-start-with-everyday-customer-interviews/"
status = 301

[[redirects]]
from = "/newsletter/how-to-use-the-extended-competitive-landscape/"
to = "/en/blog/how-to-use-the-extended-competitive-landscape/"
status = 301

[[redirects]]
from = "/newsletter/are-surveys-useful-for-product-development/"
to = "/en/blog/are-surveys-useful-for-product-development/"
status = 301

[[redirects]]
from = "/newsletter/customer-research-for-treasure-hunting-pirates/"
status = 301
to = ""/en/blog/customer-research-for-treasure-hunting-pirates/"