collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog EN" # Used in the UI
    folder: "src/content/blog/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Create "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
media_folder: "src/content/blog/images" # Location where files will be stored in the repo
public_folder: "src/content/blog/images" # The src attribute for uploaded media
display_url: "https://utxo.solutions"
site_url: "https://utxo.solutions"