collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    media_folder: "images"
    public_folder: "images"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "secret", widget: "boolean", default: false, required: false}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog EN" # Used in the UI
    folder: "src/content/blog/en" # The path to the folder where the documents are stored
    media_folder: "../images"
    public_folder: "../images"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "secret", widget: "boolean", default: false, required: false}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service"
    label: "Service"
    folder: "src/content/services"
    media_folder: "images"
    public_folder: "images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Icon", name: "icon", widget: "string", required: false, default: "flaticon-round-table" }
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        required: false
        fields:
          - label: "Hide Contact Form"
            name: "hideContactForm"
            widget: "boolean"
            default: false
            required: false
          - label: "Download Title"
            name: "downloadTitle"
            widget: "string"
            required: false
          - label: "Download Text"
            name: "downloadText"
            widget: "string"
            required: false
          - label: "Download Link"
            name: "downloadLink"
            widget: "string"
            required: false
          - label: "Download Button Text"
            name: "downloadButtonLabel"
            widget: "string"
            required: false
          - label: "Download Button Icon (Fontawesome)"
            name: "downloadButtonIcon"
            widget: "string"
            default: "fa-file-pdf"
            required: false
      - label: "FAQ"
        name: "questions"
        widget: "list"
        required: false
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
          - label: "Answer"
            name: "answer"
            widget: "text"
      - label: "Call To Action"
        name: "ctaSection"
        widget: "object"
        required: false
        fields:
          - label: "Download Text"
            name: "title"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Button Text"
            name: "buttonLabel"
            widget: "string"
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service-en"
    label: "Service EN"
    folder: "src/content/services/en"
    media_folder: "../images"
    public_folder: "../images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Icon", name: "icon", widget: "string", required: false, default: "flaticon-round-table" }
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        required: false
        fields:
          - label: "Hide Contact Form"
            name: "hideContactForm"
            widget: "boolean"
            default: false
          - label: "Download Title"
            name: "downloadTitle"
            widget: "string"
          - label: "Download Text"
            name: "downloadText"
            widget: "string"
          - label: "Download Link"
            name: "downloadLink"
            widget: "string"
          - label: "Download Button Text"
            name: "downloadButtonLabel"
            widget: "string"
          - label: "Download Button Icon (Fontawesome)"
            name: "downloadButtonIcon"
            widget: "string"
            default: "fa-file-pdf"
      - label: "FAQ"
        name: "questions"
        widget: "list"
        required: false
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
          - label: "Answer"
            name: "answer"
            widget: "text"
      - label: "Call To Action"
        name: "ctaSection"
        widget: "object"
        required: false
        fields:
          - label: "Download Text"
            name: "title"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Button Text"
            name: "buttonLabel"
            widget: "string"
      - { label: "Body", name: "body", widget: "markdown" }
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Create "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
media_folder: "src/images"
public_folder: "src/images"
display_url: "https://utxo.solutions"
site_url: "https://utxo.solutions"