collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    media_folder: "images"
    public_folder: "images"
    create: true # Allow users to create new documents in this collection
    sortable_fields: ['pubDate', 'title', 'author']
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "secret", widget: "boolean", default: false, required: false}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "select", options: ["Annahmen", "Bitcoin", "Datenanalyse", "Digitalisierung", "Experimente", "Fortschrittszyklus", "Gesprächsführung", "How-To", "Hypothesen", "Innovation", "JTBD", "Künstliche Intelligenz (KI)", "Kundenforschung", "Methodik", "Nachhaltigkeit", "Partnerschaften", "Persönliches", "Podcast", "Produktentwicklung", "Rationalität", "shot", "Strategie", "Struktur", "Unternehmertum"], multiple: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog EN" # Used in the UI
    folder: "src/content/blog/en" # The path to the folder where the documents are stored
    media_folder: "../images"
    public_folder: "../images"
    create: true # Allow users to create new documents in this collection
    sortable_fields: ['pubDate', 'title', 'author']
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "secret", widget: "boolean", default: false, required: false}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "select", options: ["Annahmen", "Bitcoin", "Datenanalyse", "Digitalisierung", "Experimente", "Fortschrittszyklus", "Gesprächsführung", "How-To", "Hypothesen", "Innovation", "JTBD", "Künstliche Intelligenz (KI)", "Kundenforschung", "Methodik", "Nachhaltigkeit", "Partnerschaften", "Persönliches", "Podcast", "Produktentwicklung", "Rationalität", "shot", "Strategie", "Struktur", "Unternehmertum"], multiple: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Canonical URL", name: "canonicalURL", widget: "string", required: false }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Reference", name: "reference", widget: "string", hint: "Unique handle to link posts between languages.", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service"
    label: "Service"
    folder: "src/content/services"
    media_folder: "images"
    public_folder: "images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Icon", name: "icon", widget: "string", required: false, default: "flaticon-round-table" }
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        required: false
        fields:
          - label: "Hide Contact Form"
            name: "hideContactForm"
            widget: "boolean"
            default: false
            required: false
          - label: "Download Title"
            name: "downloadTitle"
            widget: "string"
            required: false
          - label: "Download Text"
            name: "downloadText"
            widget: "string"
            required: false
          - label: "Download Link"
            name: "downloadLink"
            widget: "string"
            required: false
          - label: "Download Button Text"
            name: "downloadButtonLabel"
            widget: "string"
            required: false
          - label: "Download Button Icon (Fontawesome)"
            name: "downloadButtonIcon"
            widget: "string"
            default: "fa-file-pdf"
            required: false
      - label: "FAQ"
        name: "questions"
        widget: "list"
        required: false
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
          - label: "Answer"
            name: "answer"
            widget: "text"
      - label: "Call To Action"
        name: "ctaSection"
        widget: "object"
        required: false
        fields:
          - label: "Download Text"
            name: "title"
            widget: "string"
            required: false
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
            required: false
          - label: "Button Text"
            name: "buttonLabel"
            widget: "string"
            required: false
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "service-en"
    label: "Service EN"
    folder: "src/content/services/en"
    media_folder: "../images"
    public_folder: "../images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", default: "{{now}}" }
      - { label: "Featured Image", name: "previewImage", widget: "image", required: false }
      - { label: "Icon", name: "icon", widget: "string", required: false, default: "flaticon-round-table" }
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        required: false
        fields:
          - label: "Hide Contact Form"
            name: "hideContactForm"
            widget: "boolean"
            default: false
          - label: "Download Title"
            name: "downloadTitle"
            widget: "string"
            required: false
          - label: "Download Text"
            name: "downloadText"
            widget: "string"
            required: false
          - label: "Download Link"
            name: "downloadLink"
            widget: "string"
            required: false
          - label: "Download Button Text"
            name: "downloadButtonLabel"
            widget: "string"
            required: false
          - label: "Download Button Icon (Fontawesome)"
            name: "downloadButtonIcon"
            widget: "string"
            required: false
            default: "fa-file-pdf"
      - label: "FAQ"
        name: "questions"
        widget: "list"
        required: false
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
          - label: "Answer"
            name: "answer"
            widget: "text"
      - label: "Call To Action"
        name: "ctaSection"
        widget: "object"
        required: false
        fields:
          - label: "Download Text"
            name: "title"
            widget: "string"
            required: false
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
            required: false
          - label: "Button Text"
            name: "buttonLabel"
            widget: "string"
            required: false
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Seiten
    extension: mdx
    format: frontmatter
    files:
      - name: tools
        label: Tools
        file: "/src/pages/tools.mdx"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: "Blog"
            name: "blog"
            widget: "object"
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                default: false
              - label: Subtitle
                name: subtitle
                widget: string
                required: false
              - label: Description
                name: description
                widget: markdown
                required: false
              - { label: "Body", name: "body", widget: "markdown" }
      - name: bitcoin
        label: Bitcoin
        file: "/src/pages/bitcoin.mdx"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: "Blog"
            name: "blog"
            widget: "object"
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                default: false
              - label: Subtitle
                name: subtitle
                widget: string
                required: false
              - label: Description
                name: description
                widget: markdown
                required: false
              - { label: "Body", name: "body", widget: "markdown" }
      - name: index
        label: Startseite
        file: /src/pages/index.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Intro Text, name: intro, widget: string}
              - {label: Button Text, name: ctaText, widget: string}
              - {label: Button Link, name: ctaLink, widget: string}
          - label: Über uns
            name: about
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Text 2, name: text2, widget: markdown}
              - {label: Video URL, name: video, widget: string}
              - {label: Bulletpoints, name: bulletpoints, min: 4, max: 6, widget: list}
              - label: Boxes,
                name: boxes
                min: 2
                max: 2
                widget: list
                fields:
                  - name: label
                    label: Label
                    widget: string
                  - name: number
                    label: Number
                    widget: string
                  - name: icon
                    label: Icon
                    widget: string
          - label: Services
            name: services
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - name: title
                    label: Title
                    widget: string
                  - name: text
                    label: Text
                    widget: string
                  - name: link
                    label: Link
                    widget: string
                  - name: linkLabel
                    label: Link Label
                    widget: string
                    required: false
                  - name: icon
                    label: Icon
                    widget: string
          - label: Kunden
            name: clients
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
          - label: Call To Action
            name: ctaSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Button Label, name: buttonLabel, widget: string}
              - {label: Button Link, name: buttonLink, widget: string}
          - label: Testimonials
            name: testimonials
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - name: author
                    label: Author
                    widget: string
                  - name: position
                    label: Position
                    widget: string
                  - name: quote
                    label: Quote
                    widget: string
                  - name: image
                    label: Image
                    widget: string
          - label: Blog
            name: blog
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Description, name: description, widget: string}
      - name: index-en
        label: Startseite EN
        file: /src/pages/en/index.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Intro Text, name: intro, widget: string}
              - {label: Button Text, name: ctaText, widget: string}
              - {label: Button Link, name: ctaLink, widget: string}
          - label: Über uns
            name: about
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Text 2, name: text2, widget: markdown}
              - {label: Video URL, name: video, widget: string}
              - {label: Bulletpoints, name: bulletpoints, min: 4, max: 6, widget: list}
              - label: Boxes,
                name: boxes
                min: 2
                max: 2
                widget: list
                fields:
                  - name: label
                    label: Label
                    widget: string
                  - name: number
                    label: Number
                    widget: string
                  - name: icon
                    label: Icon
                    widget: string
          - label: Services
            name: services
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - name: title
                    label: Title
                    widget: string
                  - name: text
                    label: Text
                    widget: string
                  - name: link
                    label: Link
                    widget: string
                  - name: linkLabel
                    label: Link Label
                    widget: string
                    required: false
                  - name: icon
                    label: Icon
                    widget: string
          - label: Kunden
            name: clients
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
          - label: Call To Action
            name: ctaSection
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Button Label, name: buttonLabel, widget: string}
              - {label: Button Link, name: buttonLink, widget: string}
          - label: Testimonials
            name: testimonials
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - name: author
                    label: Author
                    widget: string
                  - name: position
                    label: Position
                    widget: string
                  - name: quote
                    label: Quote
                    widget: string
                  - name: image
                    label: Image
                    widget: string
          - label: Blog
            name: blog
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Description, name: description, widget: string}
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Create "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
media_folder: "src/images"
public_folder: "src/images"
display_url: "https://utxo.solutions"
site_url: "https://utxo.solutions"